name: pytton pipeline
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: python hello.py
  build: 
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/upload-artifacts@v3
        with:
          name: hello
          path: .
